frontend/forms/roles.py
import httpx
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

from http import HTTPStatus

from frontend.config import app_config

url = f'{app_config.backend_url}/roles/'


class CreateRoleForm(FlaskForm):
    name = StringField(
        'Role name',
        validators=[DataRequired()],
        render_kw={"class": "form-control"},
    )
    submit = SubmitField('Create', render_kw={"class": "btn btn-success"})

    def create_role(self) -> bool:
        data = {'name': self.name.data}
        answer = httpx.post(url, json=data)
        if answer.status_code != HTTPStatus.CREATED:
            return False

        return True


class UpdateRoleForm(FlaskForm):
    name = StringField(
        'Updated role name',
        validators=[DataRequired()],
        render_kw={"class": "form-control"},
    )
    submit = SubmitField('Update', render_kw={"class": "btn btn-primary"})

    def update_role(self, role_id: int) -> bool:
        data = {'name': self.name.data}
        answer = httpx.put(f'{url}{role_id}', json=data)
        if answer.status_code != HTTPStatus.OK:
            return False

        return True


class DeleteRoleForm(FlaskForm):
    submit = SubmitField('Delete', render_kw={"class": "btn btn-danger"})

    def delete_role(self, role_id: int) -> bool:
        answer = httpx.delete(f'{url}{role_id}')
        if answer.status_code != HTTPStatus.NO_CONTENT:
            return False

        return True

frontend/forms/users.py
import httpx
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired

from http import HTTPStatus

from frontend.config import app_config

url = f'{app_config.backend_url}/users/'


class CreateUserForm(FlaskForm):
    name = StringField(
        'User name',
        validators=[DataRequired()],
        render_kw={"class": "form-control"},
    )
    submit = SubmitField('Create', render_kw={"class": "btn btn-success"})

    def create_user(self) -> bool:
        data = {'name': self.name.data}
        answer = httpx.post(url, json=data)
        if answer.status_code != HTTPStatus.CREATED:
            return False

        return True


class UpdateUserForm(FlaskForm):
    name = StringField(
        'Updated user name',
        validators=[DataRequired()],
        render_kw={"class": "form-control"},
    )
    submit = SubmitField('Update', render_kw={"class": "btn btn-primary"})

    def update_user(self, user_id: int) -> bool:
        data = {'name': self.name.data}
        answer = httpx.put(f'{url}{user_id}', json=data)
        if answer.status_code != HTTPStatus.OK:
            return False

        return True


class DeleteUserForm(FlaskForm):
    submit = SubmitField('Delete', render_kw={"class": "btn btn-danger"})

    def delete_user(self, user_id: int) -> bool:
        answer = httpx.delete(f'{url}{user_id}')
        if answer.status_code != HTTPStatus.NO_CONTENT:
            return False

        return True


class AddRoleToUserForm(FlaskForm):
    role_select = SelectField('Add role to user', coerce=int, render_kw={"class": "form-select"})
    submit = SubmitField('Add role', render_kw={"class": "btn btn-success"})

    def add_role_to_user(self, user_id: int) -> bool:
        data = {"role_id": self.role_select.data}
        answer = httpx.post(f'{url}{user_id}/roles', json=data)
        if answer.status_code != HTTPStatus.CREATED:
            return False

        return True


class RemoveRoleFromUserForm(FlaskForm):
    role_select = SelectField(
        'Remove role from user',
        coerce=int,
        render_kw={"class": "form-select"},
    )
    submit = SubmitField('Remove role', render_kw={"class": "btn btn-warning"})

    def remove_role_from_user(self, user_id: int) -> bool:
        answer = httpx.delete(f'{url}{user_id}/roles/{self.role_select.data}')
        if answer.status_code != HTTPStatus.NO_CONTENT:
            return False

        return True

frontend/app.py
from flask import Flask

from frontend.config import app_config
from frontend.views import index, role, user


def create_app():
    app = Flask(__name__)

    app.config['SECRET_KEY'] = app_config.secret_key

    app.register_blueprint(index.view)
    app.register_blueprint(role.view, url_prefix='/roles')
    app.register_blueprint(user.view, url_prefix='/users')

    return app

frontend/views/index.py
from flask import Blueprint, render_template, redirect, url_for

from frontend.client.api import client
from frontend.forms.roles import CreateRoleForm
from frontend.forms.users import CreateUserForm

view = Blueprint('index', __name__)


@view.route('/')
def index():
    users = client.users.get_all()

    roles = client.roles.get_all()
    roles_with_users = []
    for role in roles:
        users_of_role = client.roles.get_users(uid=role.uid)
        role_with_users = role.dict()
        user_names = ', '.join([user.name for user in users_of_role])
        role_with_users['users'] = user_names
        roles_with_users.append(role_with_users)

    user_form = CreateUserForm()
    role_form = CreateRoleForm()

    return render_template(
        'index.html',
        users=[user.dict() for user in users],
        roles=roles_with_users,
        user_form=user_form,
        role_form=role_form,
        page_title='User-Role demo',
    )


@view.route('/add_user', methods=['POST'])
def add_user():
    user_form = CreateUserForm()
    if user_form.validate_on_submit():
        if user_form.create_user():
            return redirect(url_for('index.index'))


@view.route('/add_role', methods=['POST'])
def add_role():
    role_form = CreateRoleForm()
    if role_form.submit.data and role_form.validate():
        if role_form.create_role():
            return redirect(url_for('index.index'))

frontend/views/role.py
from flask import Blueprint, render_template, redirect, url_for, request

from frontend.client.api import client
from frontend.forms.roles import DeleteRoleForm, UpdateRoleForm

view = Blueprint('roles', __name__)


@view.route('/<uid>', methods=['GET', 'POST'])
def role(uid):
    role = client.roles.get_by_id(uid)
    title = role.name

    update_form = UpdateRoleForm(csrf_enabled=False)
    if update_form.validate_on_submit():
        if update_form.update_role(role_id=uid):
            return redirect(request.url)

    delete_form = DeleteRoleForm()
    if delete_form.validate_on_submit():
        if delete_form.delete_role(role_id=uid):
            return redirect(url_for('index.index'))

    return render_template(
        'role.html',
        page_title=title,
        role=role.dict(),
        update_form=update_form,
        delete_form=delete_form,
    )

frontend/views/user.py
from flask import Blueprint, render_template, redirect, url_for, request

from frontend.client.api import client
from frontend.forms.users import DeleteUserForm, UpdateUserForm
from frontend.forms.users import AddRoleToUserForm, RemoveRoleFromUserForm

view = Blueprint('users', __name__)


@view.route('/<int:uid>', methods=['GET', 'POST'])
def user(uid):
    user = client.users.get_by_id(uid)
    roles = client.roles.get_all()
    added_roles = client.users.get_roles(uid)
    available_roles = [role for role in roles if role not in added_roles]
    title = user.name

    update_form = UpdateUserForm(csrf_enabled=False)
    if update_form.validate_on_submit():
        if update_form.update_user(user_id=uid):
            return redirect(request.url)

    add_role_form = AddRoleToUserForm()
    role_choices = [(role.uid, role.name) for role in available_roles]
    add_role_form.role_select.choices = role_choices
    if add_role_form.validate_on_submit():
        if add_role_form.add_role_to_user(uid):
            return redirect(request.url)

    remove_role_form = RemoveRoleFromUserForm()
    remove_role_form.role_select.choices = [(role.uid, role.name) for role in added_roles]
    if remove_role_form.validate_on_submit():
        if remove_role_form.remove_role_from_user(uid):
            return redirect(request.url)

    delete_form = DeleteUserForm()
    if delete_form.validate_on_submit():
        if delete_form.delete_user(user_id=uid):
            return redirect(url_for('index.index'))

    return render_template(
        'user.html',
        page_title=title,
        user=user.dict(),
        added_roles=', '.join([role.name for role in added_roles]),
        update_form=update_form,
        delete_form=delete_form,
        add_role_form=add_role_form,
        remove_role_form=remove_role_form,
    )

frontend/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ page_title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    {% include 'navbar.html' %}
    <p></p>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

frontend/templates/index.html
{% extends "base.html" %}

{% block content %}
<html>
  <body>
    <div class="row">
        <div class="col-4">
            <h4>Users:</h4>
            <form action="{{ url_for('index.add_user') }}" method="post">
                {{ user_form.hidden_tag() }}
                <div class="form-group">
                  {{ user_form.name.label }}
                  {{ user_form.name() }}
                </div>
                <p></p>
                {{ user_form.submit }}
            </form>
            <p></p>
            {% include 'user_table.html' %}
        </div>
        <div class="col-2"></div>
        <div class="col-4">
            <h4>Roles:</h4>
            <form action="{{ url_for('index.add_role') }}" method="post">
                {{ role_form.hidden_tag() }}
                <div class="form-group">
                  {{ role_form.name.label }}
                  {{ role_form.name() }}
                </div>
                <p></p>
                {{ role_form.submit }}
            </form>
            <p></p>
            {% include 'role_table.html' %}
        </div>
    </div>
  </body>
</html>
{% endblock %}

frontend/templates/navbar.html
<nav class="navbar" style="background-color: #00ca5b4b;">
    <div class="container-fluid">
      <a class="navbar-brand mb-0 h1" href="/">User-Role demo</a>
    </div>
</nav>

frontend/templates/role.html
{% extends "base.html" %}

{% block content %}
<html>
  <body>
    <div class="row">
        <div class="col-4">
        </div>
        <div class="col-4">
            <h5>Role {{ role.name }}</h5><p></p>
            <h6>Role id: {{ role.uid }}</h6>
            <form method="post">
                {{ update_form.hidden_tag() }}
                <div class="form-group">
                  {{ update_form.name.label }}
                  {{ update_form.name() }}
                </div>
                <p></p>
                {{ update_form.submit }}
            </form>
            <p></p>
            <form method="post">
                {{ delete_form.hidden_tag() }}
                {{ delete_form.submit }}
            </form>
        </div>
        <div class="col-4">
        </div>
    </div>
  </body>
</html>
{% endblock %}

frontend/templates/role_table.html
<table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Users</th>
      </tr>
    </thead>
    <tbody>
        {% for i in range(roles | length) %}
            <tr>
                <th scope="row">{{  i + 1  }}</th>
                <td><h6>{{ roles[i].name }}</h6></td>
                <td>{{ roles[i].users }}</td>
            </tr>            
        {% endfor %}                
    </tbody>
</table>

frontend/templates/user.html
{% extends "base.html" %}

{% block content %}
<html>
  <body>
    <div class="row">
        <div class="col-4">
        </div>
        <div class="col-4">
            <h5>User {{ user.name }}</h5><p></p>
            <h6>User id: {{ user.uid }}</h6>
            <h6>Assigned roles: {{ added_roles }}</h6>
            <form method="post">
                {{ update_form.hidden_tag() }}
                <div class="form-group">
                  {{ update_form.name.label }}
                  {{ update_form.name() }}
                </div>
                <p></p>
                {{ update_form.submit }}
            </form>
            <p></p>
            <form method="post">
                {{ delete_form.hidden_tag() }}
                {{ delete_form.submit }}
            </form>
            <p></p>
            <form method="post">
                {{ add_role_form.hidden_tag() }}
                <div class="form-group">
                  {{ add_role_form.role_select.label }}
                  {{ add_role_form.role_select() }}
                </div>
                <p></p>
                {{ add_role_form.submit }}
            </form>
            <p></p>
            <form method="post">
                {{ remove_role_form.hidden_tag() }}
                <div class="form-group">
                  {{ remove_role_form.role_select.label }}
                  {{ remove_role_form.role_select() }}
                </div>
                <p></p>
                {{ remove_role_form.submit }}
            </form>
        </div>
        <div class="col-4">
        </div>
    </div>
  </body>
</html>
{% endblock %}

frontend/templates/user_table.html
<table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
      </tr>
    </thead>
    <tbody>
        {% for i in range(users | length) %}
            <tr>
                <th scope="row">{{  i + 1  }}</th>
                <td>
                  <h6><a href="{{ url_for('users.user', uid=users[i].uid) }}" >{{ users[i].name }}</a></h6>
                </td>
            </tr>            
        {% endfor %}                
    </tbody>
</table>